// <auto-generated />
using System;
using BetterHealthCareAPI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BetterHealthCareAPI.Migrations
{
    [DbContext(typeof(BetterHealthCareDbContext))]
    [Migration("20250629122942_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("BetterHealthCareAPI.Domain.Models.MedicalFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base64")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PatientActionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatientActionId");

                    b.ToTable("MedicalFiles");
                });

            modelBuilder.Entity("BetterHealthCareAPI.Domain.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("BetterHealthCareAPI.Domain.Models.PatientAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfProcedure")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hospital")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProcedureId");

                    b.ToTable("PatientActions");
                });

            modelBuilder.Entity("BetterHealthCareAPI.Domain.Models.Procedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Procedures");
                });

            modelBuilder.Entity("BetterHealthCareAPI.Domain.Models.MedicalFile", b =>
                {
                    b.HasOne("BetterHealthCareAPI.Domain.Models.PatientAction", null)
                        .WithMany("Files")
                        .HasForeignKey("PatientActionId");
                });

            modelBuilder.Entity("BetterHealthCareAPI.Domain.Models.PatientAction", b =>
                {
                    b.HasOne("BetterHealthCareAPI.Domain.Models.Patient", null)
                        .WithMany("PatientActions")
                        .HasForeignKey("PatientId");

                    b.HasOne("BetterHealthCareAPI.Domain.Models.Procedure", "Procedure")
                        .WithMany()
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("BetterHealthCareAPI.Domain.Models.Patient", b =>
                {
                    b.Navigation("PatientActions");
                });

            modelBuilder.Entity("BetterHealthCareAPI.Domain.Models.PatientAction", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
